services:
  cryo_linux:
    env_file:
      - .env
    build:
      args:
        - C_PORT=${C_PORT}
        - GIT_TOKEN=${GIT_TOKEN}
        - GIT_USERNAME=${GIT_USERNAME}
      context: .
      dockerfile: ./arduino.dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    volumes:
      - "${HOST_PATH}:/mnt/${HOST_PATH}"
      - "/dev:/dev"
    ports:
      - "${HOST_PORT}:${C_PORT}"
    tty: false
    stdin_open: true
    command: /bin/bash
    container_name: ${C_NAME}
    privileged: true

