[env]
TERM = "xterm-256color"

[window]
title = "Cryo's Alacrittew"
dynamic_title = false

[font]
normal.family = "Cousine Nerd font"
size = 15

[selection]
save_to_clipboard = true

[general]
# Alacritty Config

import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml",
]

[terminal]
shell = { program = "/opt/homebrew/bin/nu" }
