services:
  cryo_linux:
    build:
      context: .
      dockerfile: ./cryo_linux.dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "3005:3005"
    tty: true
    stdin_open: true
    command: /bin/bash
