# Alacritty Config

import = [
    "C:\\Users\\arvin\\AppData\\Roaming\\alacritty\\catppuccin-frappe.toml",
]

[shell]
program = "C:\\Program Files\\PowerShell\\7\\pwsh.exe"

[env]
TERM = "xterm-256color"

[window]
title = "Cryo's Alacrittew"
dynamic_title = false

[font]
normal.family = "CodeNewRoman Nerd font"
size = 15

[selection]
save_to_clipboard = true
