services:
  cryo_linux:
    env_file:
      - .env
    build:
      args:
        - C_PORT=${C_PORT}
      context: .
      dockerfile: ./cryo_linux.dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    volumes:
      - "${HOST_PATH}:/mnt/${HOST_PATH}"
      - "/dev:/dev"
#https://stackoverflow.com/questions/24225647/docker-a-way-to-give-access-to-a-host-usb-or-serial-device. Gives access to all devices on windows, dynamically too. Security flaw but, for a dev container thats alright.
    ports:
      - "${HOST_PORT}:${C_PORT}"
    tty: true
    stdin_open: true
    command: /bin/bash
    container_name: ${C_NAME}
    privileged: true

#env: HOST_PATH="C:/"
#IN_PORT=3005
#OUT_PORT=3005
#C_NAME=colx
