#cloud-config
user:
  name: ubuntu
  hashed_passwd: $6$F/LxWd/QlsXSYbC3$Wx7tjN3THEtVHf55sGvsj.NBPsNmsEk0Yc5YGLR/MO8LDFaKYkliEbJ1j67RHIRVOjh6IWeQ1RtdYvNPl1dqF/
  lock_passwd: false
  sudo: ["ALL=(ALL) NOPASSWD:ALL"]
ssh_pwauth: true
package_update: true
package_upgrade: true
#Generate passwd with mkpasswd --method=SHA-512 --rounds=4096 https://cloudinit.readthedocs.io/en/latest/reference/examples.html Not tryna be secure, just trying to avoid normal string representation. This is insecure anyway, even with 5 million rounds.
