#cloud-config
user:
  name: ubuntu
  hashed_passwd: $6$rounds=4096$xw39jhl/TKe7Bevk$FkABLzD9gvq57.gcMaZLpUJBrzBK1XuwI.ghBm4.vURn6X8EIIsnTNFzZODWRUbEIBFIzAVfkcP7kdzI8uz93/
ssh_pwauth: true
package_update: true
package_upgrade: true
#Generate passwd with mkpasswd --method=SHA-512 --rounds=4096 https://cloudinit.readthedocs.io/en/latest/reference/examples.html Not tryna be secure, just trying to avoid normal string representation. This is insecure anyway, even with 5 million rounds.
